name: app_reporte_humanidad
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  equatable: ^1.2.6
  get_it: ^5.0.6
  flutter_bloc: ^6.1.3

  shared_preferences: ^0.5.12+4
  http: ^0.12.2
  local_auth: ^0.6.3+4
  package_info: ^0.4.3+4
  device_info: ^1.0.0
  firebase_core: ^0.5.0+1
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^4.0.0

  feather_icons_flutter: ^4.7.4
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.1
  flutter_svg: ^0.19.1
  date_range_picker: ^1.0.6
  month_picker_dialog: ^0.3.3

  uuid: ^2.2.2
  imei_plugin: ^1.2.0
  flutter_swipe_action_cell: ^1.3.4
  flutter_launcher_icons: ^0.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo_cuadrado.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/svg/undraw/
    - assets/background/
    - assets/icon_buttons/
